### ISSUE TITLE
Contributing to the source code

### ISSUE THREAD

**Issue by michaelvantelgen-Arcadis** [Dlubal-Software/Dlubal_CSharp_Client#10]
Hi @jarabroz,

I have a suggestion to multi target different frameworks but I cannot seem to push my commit to the repository. I get an error message:

> Failed to push the branch to the remote repository. See the Output window for more details.
> Pushing michaelvantelgen-Arcadis_Multi_Framework_Targetting
> Failed to push the branch to the remote repository. See the Output window for more details.
> Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
> Git failed with a fatal error.
> unable to access 'https://github.com/Dlubal-Software/Dlubal_CSharp_Client/': The requested URL returned error: 403

Any ideas on how to solve this?

**Comment by jarabroz** [comment]
Hi @michaelvantelgen-Arcadis ,

We have enabled branch policy for main brach. If you want to contribute, please follow [guide for contributing]
(CONTRIBUTING.md). In brief, you need to have your branch and create Pull Request.

**Comment by michaelvantelgen-Arcadis** [comment]
Hi @jarabroz , I have created that branch locally but cannot push it to remote. Branch name is michaelvantelgen-Arcadis_Multi_Framework_Targetting as per [contribution instructions](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/blob/main/CONTRIBUTING.md).

**Comment by jarabroz** [comment]
Hi @michaelvantelgen-Arcadis,
I made a mistake. I thought that it would be possible to contribute without forking of repository. We have experience of contributing to the organization's repos not with outside collaborators.
I have just tested the workflow with a fork, and it worked for me. I found steps [here](https://docs.github.com/en/get-started/quickstart/contributing-to-projects).
Let me know if forking works for you.

**Comment by michaelvantelgen-Arcadis** [comment]
Hi @jarabroz, see https://github.com/Dlubal-Software/Dlubal_CSharp_Client/pull/16

Again I don't mind if you reject the pull but please consider this for those who are still working with older frameworks.

Thank you,
Michael

**Comment by jarabroz** [comment]
Hi @michaelvantelgen-Arcadis,

I have just approved code review #16   and your changes have been merged. 

We succeeded with our first contribution.  Thank you, you was the first one.
