### ISSUE TITLE
BUG: RfemModelClient finish_modification() doesn't respond

### ISSUE THREAD

**Issue by michaelvantelgen-Arcadis** [Dlubal-Software/Dlubal_CSharp_Client#11]
**Describe the bug**
Using RfemModelClient I cannot finish modification of the model using finish_modification(). This does not seam to respond to the command and the dialog in RFEM doesn't disappear.
![image](https://user-images.githubusercontent.com/79198701/146023460-e9cad178-8579-48c9-871e-718da940d40f.png)
When doing the finish_modification() twice I get an error message in my IDE and the dialog does disappear.
![image](https://user-images.githubusercontent.com/79198701/146023663-b960b05a-9706-4b2e-957d-716ea19643bb.png)
The error did not occur before pulling the latest commit. Did anything change? I haven't tested RSTAB - I don't have that application

**To Reproduce**
1. Do any modification in the model
2. Finish the modification using finish_modification() with the RfemModelClient 

**Expected behavior**
Expected the model's modification to finish and the pop-up message to disappear.

**Desktop (please complete the following information):**
 - OS: WIN 10 21H1
 - Version of RFEM6.01.0003
 - Version of library: latest

**Comment by jarabroz** [comment]
Hello @michaelvantelgen-Arcadis,
Dialogue from your screenshot tells you that model is locked for direct modifications in UI.  You are setting BasicHttpBinding.
```Csharp
private static BasicHttpBinding Binding
        {
            get
            {
                BasicHttpBinding binding = new BasicHttpBinding
                {
                    // Send timeout is set to 180 seconds.
                    SendTimeout = new TimeSpan(0, 0, 180),
                    UseDefaultWebProxy = true,
                };

                return binding;
            }
        }
```
Here you can set timeout. Above, after 180s of idle state model is unlocked. You notify RFEM with begin_modification that you will do changes with model and then you need to use finish_modification or cancel_modification to end it. Then counting for idle starts.

**Comment by michaelvantelgen-Arcadis** [comment]
Hi @jarabroz , 

Ok so I played around with putting other values but no matter what I specify, the message only disappears after about 90 seconds after the last modification.

Any thoughts? Will try some other things too.
