### ISSUE TITLE
BUG:Crashes when trying to create an imperfection_case  over API

### ISSUE THREAD

**Issue by talSas** [Dlubal-Software/Dlubal_CSharp_Client#13]
**Describe the bug**
Rstab9 Crashes when trying to create an imperfection_case with the type imperfection_case_type.IMPERFECTION_TYPE_IMPERFECTION_CASES_GROUP, using the Web APi
**To Reproduce**
Create Imperfaction_case over API:

Code: 
public void TestImperfectionCreation()
		{
			imperfection_case imperfection_Case = new imperfection_case();
			imperfection_Case.no = 9864;
			imperfection_Case.reference_nodeSpecified = true;
			imperfection_Case.type = imperfection_case_type.IMPERFECTION_TYPE_IMPERFECTION_CASES_GROUP;
			imperfection_Case.typeSpecified = true;
			rstab9ModelClient.set_imperfection_case(imperfection_Case);
                        //without type IMPERFECTION_TYPE_IMPERFECTION_CASES_GROUP rs dont crash
		}
**Expected behavior**
create a groupe of imperfections

**Screenshots**

**Desktop (please complete the following information):**
 -  WIN 10
 - RS9.01.0011.167
 - 1.0.9

**Additional context**

I'm not sure if this is your responsibility, if not I would be grateful for a forwarding, screenshots and .dmps I have attached, as well as the rs9 model

Screenshots:
![error1](https://user-images.githubusercontent.com/83770956/146215122-9cdcf7c3-e6b0-4a0f-a0b1-ac26437344a1.JPG)
![error2](https://user-images.githubusercontent.com/83770956/146215126-bacbf011-b61b-4d0d-abb6-9c3f95a655bf.JPG)
![errorFinish](https://user-images.githubusercontent.com/83770956/146215130-0eb03110-e81c-4c27-99d7-8e8c88569d8f.JPG)
![Work](https://user-images.githubusercontent.com/83770956/146215135-72b2f60d-d65c-4cd8-ba7c-02e5446f497d.JPG)

.dmp and modell:
[imperfectionError.zip](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/files/7720722/imperfectionError.zip)

**Comment by talSas** [comment]
ok i think the error is because i am trying to create an empty groupe, regardless the crash is rather inconvenient.

furthermore i found another "error" while trying to find a solution. 

It is not possible to process imperfections with the type imperfection_case_type.IMPERFECTION_TYPE_LOCAL_IMPERFECTIONS_ONLY.

![grafik](https://user-images.githubusercontent.com/83770956/146333051-6ee9808e-b91b-49ef-a21c-64ea4f459b37.png)

**Comment by jarabroz** [comment]
Hi @talSas,

do you still have problems with imperfections?
