### ISSUE TITLE
FEATURE: Close 'Application is locked' dialog using code command

### ISSUE THREAD

**Issue by michaelvantelgen-Arcadis** [Dlubal-Software/Dlubal_CSharp_Client#15]
**Is your feature request related to a problem? Please describe.**
Following [/issues/11], I think we need a command to close the 'Application is locked' dialog.

The reason the dialog is closing in the Cantilever example, is because the console application is exited (the command prompt itself doesn't need to be closed). 

When you create a Form or a library for another application, the 'script' isn't closed, resulting in the dialog remaining opened. If you then close the Form or alternatively an application containing the library, the dialog disappears. 

If no action is taken, the dialog remains opened exactly 90 seconds after the script is run. This is not influenced by any of the BasicHttpBinding setting possibilities.

**Describe the solution you'd like**
A method in RfemSoapWsCoreClient that closes the dialog, so you don't have to wait 90 seconds for the dialog to timeout.

**Describe alternatives you've considered**
Saving, closing and reopening the RFEM model but it seams a bad (slow) workaround.

**Additional context**
![image](https://user-images.githubusercontent.com/79198701/146899437-f859ee01-e73f-4de7-b7b0-5a97c83c6522.png)

**Comment by jarabroz** [comment]
We have created mechanism which close connection directly.
