### ISSUE TITLE
FEATURE: some API requests are missing in the client

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/Dlubal_CSharp_Client#19]
**Problem**
This client does not contain all requests that are already available using SOAP
As an example getting model settings and options is possible using /get_model_settings_and_options 

**Describe the solution you'd like**
As the code suggests you are using a automated tool to build this library. Please add the missing requests to your build system.

**Describe alternatives you've considered**
Forking the repo and adding these information by hand is cumbersome and error prone.

**Comment by jarabroz** [comment]
Updated to X.02.018 version
