### ISSUE TITLE
FEATURE: NET CORE 6

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/Dlubal_CSharp_Client#20]
**NET CORE 5 is EOL**
As Microsoft has informed, NET CORE 5.0 has already reached end of life. 
[https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/)

**Describe the solution you'd like**
Please upgrade to NET CORE 6

**Comment by jarabroz** [comment]
Hello @ZTThomasOberthanner,

We are planning to upgrade to .net Core 6.0. We should be able to do it during summer. The plan is also to add an automated deployment process and more examples.

**Comment by ZTThomasOberthanner** [comment]
ok thanks, to test it I forked this library and switched to net core 6 without any problems within minutes, so this upgrade should be easy...
