### ISSUE TITLE
BUG: get_all_object_numbers optional argument required

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/Dlubal_CSharp_Client#21]
**Describe the bug**
`public int[] get_all_object_numbers(Dlubal.WS.Rfem6.Model.object_types type, int parent_no)`
parent_no is a required parameter in this client, although the SOAP API has marked this argument as optional:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rfem="http://www.dlubal.com/rfem.xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <rfem:get_all_object_numbers>
         <type>?</type>
         <!--Optional:-->
         <parent_no>?</parent_no>
      </rfem:get_all_object_numbers>
   </soapenv:Body>
</soapenv:Envelope>
```

**Expected behavior**
there should be a second method without the argument parent_no
```
public int[] get_all_object_numbers(Dlubal.WS.Rfem6.Model.object_types type)
public int[] get_all_object_numbers(Dlubal.WS.Rfem6.Model.object_types type, int parent_no)
```

**Comment by jarabroz** [comment]
This could be a hard task for us. We are generating our C# library automatically based on WSDL definition. 
Some objects needs to know parent_no. That's mainly for loading as e.g. line load is attached to some load case. So, you get all object numbers for line load for specified load case.
You can set parent_no to 0 for object without parents.

Solution could be to add overloaded method which has just one argument and handles all exceptions inside. This is possible as we have published source code of the library under open source MIT license.
