### ISSUE TITLE
FEATURE: ApplicationClient.get_model_list more than only the name

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/Dlubal_CSharp_Client#22]
**Is your feature request related to a problem? Please describe.**
Task: Try to get a list of all currently opened models in RFEM6 and work with them. 
get_model_list returns a list of model names, but you cannot query models by name

**Describe the solution you'd like**
get_model_list returns only a list of names of all models that are currently opened. 
please also add the index in the response
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <n1:get_model_listResponse xmlns:n1="http://www.dlubal.com/rfem.xsd">
         <value>
            <name>mymodel</name>

            <index>1</index> <=== add this line

         </value>
      </n1:get_model_listResponse>
   </soap:Body>
</soap:Envelope>
```
So you can access the model in the next step using `get_model()`
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rfem="http://www.dlubal.com/rfem.xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <rfem:get_model>
         <index>1</index>
      </rfem:get_model>
   </soapenv:Body>
</soapenv:Envelope>
```

**Other idea, maybe even better one**
Also include the modelurl (http://127.0.0.1:8082/) in the response so you can directly access the model without first using get_model()

**Describe alternatives you've considered**
A dirty hack would be to count the number of opened models and then run a brute force search with increasing index:
Try get_model(0), get_model(1) and so on until you find all opened models.

**Comment by jarabroz** [comment]
We have added this enhancement into our backlog for development of core WebService functionality.
