### ISSUE TITLE
FEATURE: Get user selection

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [Dlubal-Software/Dlubal_CSharp_Client#23]
**Is your feature request related to a problem? Please describe.**
In RFEM5 RF-COM it was possible to let the user pick lines, members, nodes, ... and get a list of all selected objects.

**Describe the solution you'd like**
Implementing the same behaviour could lead to time out issues in the request, so it may be better to just query the model for the current selection. This could be done by having a method similiar to `get_all_object_numbers` that just returns the object numbers for all currently selected objects: `get_all_selected_object_numbers` 

**Describe alternatives you've considered**
No idea for a workaround.

**Comment by jarabroz** [comment]
Hello @ZTThomasOberthanner,
we have implemented selection of objects. We added three operations

- clear_selection - switch off selection in application

- get_all_selected_objects - return selected object - response contain list of selected objects in application. Each element contain element type, no of element and parent no.

- set_selected_objects - switch on selection of objects in application. Structure of request is similar to previous operation (no, element type, parent no).
