### ISSUE TITLE
BUG: Missing information about No. of node at <E_MODEL_NODES SUPPORT FORCES>. 

### ISSUE THREAD

**Issue by LakuszJ** [Dlubal-Software/Dlubal_CSharp_Client#26]
**Describe the bug**
At generated XML file with results is missing information about No. of node at <E_MODEL_NODES SUPPORT FORCES>. 

**Expected behavior**
Add row with node No. 

**Screenshots**
![image](https://user-images.githubusercontent.com/97826529/183622291-e42f5d54-adaa-405a-9136-c8de2adc9003.png)

![image](https://user-images.githubusercontent.com/97826529/183622345-bec4b7c5-6319-436d-8684-4d738466fe18.png)

![image](https://user-images.githubusercontent.com/97826529/183622362-b17c385f-8eb6-4afb-907a-879d8a3d30b8.png)

**Comment by jarabroz** [comment]
We have implement WS operations for getting results tables. They contains all needed information see release #27
