### ISSUE TITLE
Documentation of available methods and valid arguments

### ISSUE THREAD

**Issue by MartinHenriksen** [Dlubal-Software/Dlubal_CSharp_Client#29]
On the developer documentation page C#-documentation is still missing, but the Python docs can give a good idea on usage in C#.
In any case it is very hard to to see what are valid method arguments when these are type string.
Example:
`RfemModelClient.begin_modification("Geometry");`
`RfemModelClient.begin_modification("Load");`
`RfemModelClient.begin_modification("Set Loads");`
These are know because they are in the provided "Cantilever" example, but I suspect there are other valid arguments.

Is there a way to see a list of valid arguments for methods exposed in the RFEMWebServiceLibrary?

**Comment by jarabroz** [comment]
@MartinHenriksen thank you for your question. 
You are right that C# documentation is still missing. We are using a code generator to generate code for our C# libraries. The generator is based on the wsdl. We are trying to find a way to add some comments to wsdl and then to the code.
You can also use a tool like SoapUI to discover API or you can use an extension for browser like Wizdler or Boomerang. You can simply write url http://localhost:8081/wsdl to address bar in the browser and you see all types and operations.
My process is that I have a model opened in application and if I want to know the data strcuture I use Wizdler to play with it and the I write C# code.

Python library is manually written. You are right it could be a hint for C# in the case of unknown objects.

**Comment by MartinHenriksen** [comment]
Thank you for the reply @jarabroz. I'll reply here instead of opening a duplicate issue although the issue is closed.

From what I can see SoapUI and the browser extensions does not give me an answer to my question. 
![image](https://user-images.githubusercontent.com/11832090/200351615-1bb16fa1-9d88-4aef-8325-d13bc4b810f1.png)
I only see a very small subset of the methods needed to interact with RFEM - nothing that is not already in the Python documentation.  
As with the example above; I still cant see valid arguments for:
`RfemModelClient.begin_modification("<what goes here>");`

Am I missing something? Or could you share some additional documentation resources?
