### ISSUE TITLE
BUG: Missing Hyperlink in Documentation on Github

### ISSUE THREAD

**Issue by talSas** [Dlubal-Software/Dlubal_CSharp_Client#3]
**Describe the bug**
The reference to the examples on the Github page leads to an error 404 - Page not found

**To Reproduce**
1. Go to '' https://github.com/Dlubal-Software/Dlubal_CSharp_Client'
2. Scroll down to 'Getting started - Steps for Visual Studio - Last Point' 
3. Click on 'examples(Hyperlink)'

**Expected behavior**
See examples about the use of the new api
**Screenshots**
![grafik](https://user-images.githubusercontent.com/83770956/143277308-39ef471b-a3df-419c-a89f-fc177df3c2b2.png)
**Desktop (please complete the following information):**
 - OS: e.g. WIN 10 2H20
 - Version of RFEM6
 - Version of tool / library [e.g. 22]

**Additional context**
This error happens on every examples hyperlink on the publish repo to C_Sharp_Client

**Comment by jarabroz** [comment]
Added first two examples.
