### ISSUE TITLE
FEATURE: Access the modal mode shapes by mesh node 6 as per RFEM5 API

### ISSUE THREAD

**Issue by Gcaussarieu** [Dlubal-Software/Dlubal_CSharp_Client#52]
**Is your feature request related to a problem? Please describe.**
We have developed a few tools which took advantage of the dynamic output from RFEM 5 to evaluate floor vibration (also available in open source here :https://github.com/knippershelbig/StructuralDesignKit_Holz)

Since RFEM 6, we cannot use it anymore.

Currently, the dynamic output are given on grid points from the surface or on intermediate result points for the members. 
This is not particularly efficient nor precise to link the information back to the FE Nodes.
Masses are already available for the mesh points.

![image](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/assets/43774443/b6368681-26b4-451e-9f9a-20def3b4752c)
![image](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/assets/43774443/2edae49b-5375-4dac-b217-98e879f7ac15)

![image](https://camo.githubusercontent.com/f83bf40db196b71c6b91ebaa59086e9b7ae08bbe54f0b818a7cf5294f194a3df/68747470733a2f2f6769746875622d70726f64756374696f6e2d757365722d61737365742d3632313064662e73332e616d617a6f6e6177732e636f6d2f34333737343434332f3233373331353136372d30323366633434622d643935332d343537382d623263392d3230633965636135366666322e676966)

In RFEM 5, also accessible through the RFEM 5 COM Interface
![image](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/assets/43774443/04212f24-0af8-45ee-b200-566237ebb20a)

**Describe the solution you'd like**
Ideally, having access to the modal mode shape (normalized displacement and rotation) by FE node as per RFEM 5 API would be great.
With the RFEM 5 API -> dynamicResults.GetNVCModeShapesOnFEPoint()

**Describe alternatives you've considered**
We are considering creating a another approach which requires creating new result objects based on the grid points and super imposing them - or looking for the closest FE node. However, this will inevitably lead to performance issue.

**Additional context**
Thank you very much for your help or other hints how to get access to this data!

Kind regards,
Guillaume

**Comment by Rebecca-Coding21** [comment]
Hi @Gcaussarieu,
at the moment it is not possible to show the modal mode shape by FE-node in RFEM 6. Because of that, these results also can't be retrieved via the API. However, it is already planned to implement this feature in the future.

**Comment by Gcaussarieu** [comment]
Hi @Rebecca-Coding21 , 
Thank you very much for your answer!

Do you have a rough idea of the timeline for when this feature will be accessible?
I'm just wondering if it is meaningful for us to invest time to find and implement a work around or if waiting is the best solution!

Best,
Guillaume

**Comment by Rebecca-Coding21** [comment]
Hi @Gcaussarieu,
unfortunately it's not possible to estimate when this feature will be available. I guess it won't be implemented within the next months.

Best regards,
Rebecca

**Comment by Gcaussarieu** [comment]
Thanks! that's already super helpful!
Best,
Guillaume
