### ISSUE TITLE
FEATURE: Get all objects from one type at once

### ISSUE THREAD

**Issue by talSas** [Dlubal-Software/Dlubal_CSharp_Client#6]
**Is your feature request related to a problem? Please describe.**

Whenever I want to perform an operation on an object type, e.g. all members, I would have to perform a query "model.get_member(int no)" for all members between 1-1000000. The problem is that the runtime with O(n) increases significantly by the number of members. For a few hundred members this might not be a problem. With a few thousand, including error handling for unoccupied numbers, it takes too long for me. 

**Describe the solution you'd like**

I would like to have a method "members[] GetAllMembers" like it was available in RS8.

**Additional context**
I add a pdf with my testcases and a dist with my sourcecode 

gist: https://gist.github.com/talSas/b7be4239d427b0f13ccdbcc63645cf43
[GetAllMemberTime.pdf](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/files/7617710/GetAllMemberTime.pdf)

**Comment by jarabroz** [comment]
There is method model.get_all_object_numbers which gives no of objects certain types. So, if you can get all member, you call get_all_object_numbers which returns int array and then go over the array and call model.get_member.
We can add some method to our C# library which could do these steps and return e.g. List.

**Comment by talSas** [comment]
> There is method model.get_all_object_numbers which gives no of objects certain types. So, if you can get all member, you call get_all_object_numbers which returns int array and then go over the array and call model.get_member. We can add some method to our C# library which could do these steps and return e.g. List.

This is good to know and reduces the runtime in the last case (8192 member and numbers from 8192 to 16383) from about 170 seconds to only 70 seconds.

But maybe there is something you can do, the RS8 method

IModelData.GetMembers(); gives me e.g. ~17 K members in less than 500 ms.

i think because it is then also only 1 api call and not over 8000 processed requests.

Regards

**Comment by ZTThomasOberthanner** [comment]
The same performance problem occurs when you want to create/update elements.: `set_member`, `set_line` just to name a few. You need to post a request for every single object. This makes the RFEM6 API so much slower than the RFEM5 API, so many existing tools cannot be ported to RFEM6 (just way to slow).

Please consider adding methods like `get_memberS` and `set_memberS` to read/send data for a batch of objects.

**Comment by jarabroz** [comment]
We will consider this enhancement in our future development
