### ISSUE TITLE
How to request result data

### ISSUE THREAD

**Issue by talSas** [Dlubal-Software/Dlubal_CSharp_Client#8]
hey,
I have now already tried a few things but somehow I do not get the results of result combinations or load case combinations or loadcase.

Could you ggfs give me some help?
the autocompletion to "Result" or something like that was not helpful until now.

 greetings

**Comment by jarabroz** [comment]
Hey @talSas,
we do not yet have a possibility to get results directly via WebService. We can export them to xml or csv files with following methods in model interface:
```CSharp
// export of detailed results
public void export_result_tables_with_detailed_members_results_to_csv(string target_directory_path);
public void export_result_tables_with_detailed_members_results_to_xml(string target_file_path);
// export of results
public void export_result_tables_to_xml(string target_file_path);
public void export_result_tables_to_csv(string target_directory_path);
```
The results is in amount of date exported. With these functions, all results for all load cases, combinations, addons are exported.
An example how to use these functions is in application is in [Cantilever example](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/blob/main/examples/Cantilever/Program.cs)
```CSharp
  model.export_result_tables_with_detailed_members_results_to_xml(CurrentDirectory + @"\Test.xml");

                string XMLFile = File.ReadAllText(CurrentDirectory + @"\Test.xml");
                XDocument doc = XDocument.Parse(XMLFile);

                foreach (XElement loadcase in doc.Descendants("load_case"))
                {
                    
                    if (loadcase.Element("no").Value == "1")
                    {
                        Console.WriteLine("My internal forces from LC 1");
                        var internalForces = loadcase.Descendants("E_MODEL_MEMBERS_INTERNAL_FORCES");
                        var internalForcesItems = internalForces.Descendants("item");
                        foreach (var item in internalForcesItems)
                        {
                            string My = item.Element("internal_force_my").Value.ToString();
                            Console.WriteLine(My);
                        }

                    }
                }
```
We have access to results via direct WebService operations in our backlog.

**Comment by talSas** [comment]
hey @jarabroz,
thanks for your detailed explanation,

do you already have a plan for when the receipt of the results directly via the web service is possible?

But with this workaround you can work for now.

regards

**Comment by talSas** [comment]
Okay as I see and understand it now it is just possible to get all or no results via export. Is it ggfs. these before the export already to sort and select.

If I need e.g. only the results of rc1001 it is inefficient to export everything.

**Comment by ZTThomasOberthanner** [comment]
+1 from my point of view, could you please add reading results directly via web service

**Comment by LakuszJ** [comment]
Hey @ZTThomasOberthanner,

I have some similar problems as You with getting results. 
I prepared the `.dll` witch provided Dictionary with objects of internal forces, maybe you will find there samthing for you. 

Link: [https://github.com/LakuszJ/JoCalc_Dlubal_Concrete_Column](url)

This `.dll`  create, `Dictionary<int, Dictionary<int, List<InternalForcesMemberSingleItem>>>`
Whre first `<TKey>` is number of the member at RFEM current model, second `<TKey>` is number of the combination. After that you will get `List<InternalForcesMemberSingleItem>`.

Examble:
```
CSVEditorAndForceGenerator fg = new CSVEditorAndForceGenerator(openAndReadModel.gIARM);
Dictionary<int, Dictionary<int, List<InternalForcesMemberSingleItem>>> dicMCF = fg.GenereteDicOfForcesForAllMembers();
List<InternalForcesMemberSingleItem> listOfForces_3_2 = dicMCF[3][2];
```
as above you will get  'List<InternalForcesMemberSingleItem>' for member no 3 and combination no 2.

Finally you will get `InternalFocesMemberSinlgeItem` with all necesery forces and `.json` file as on screen bellow.

PS. Problem with different UI language is solved by provide ResourceManager with translations by `Strings.de-DE.resx' and another.
PS2. "speccyficcationJC" it is value from comment box for member at RFEM, I will use it as some substitute of selection to filter members. 
PS3. This library getting only Combination do You have to create it before use, i don't need single load results.

![image](https://user-images.githubusercontent.com/97826529/187092006-d9fc30f5-2e56-4d40-b16b-9f49ec59274c.png)

**Comment by ZTThomasOberthanner** [comment]
Thanks for your work! I will have a look at it :-)

**Comment by jarabroz** [comment]
@LakuszJ Thank you for your work. Do you think that it would be useful for other to add your tool into our project? We could put it to the separated namespace and class. We give you full credits in our List of Contributors.

We are also working on the WebService operations for getting results directly without necessity to export it to files. It is based on the result tables which you know from application. We are close to release it for analysis results. Our desire is to continue with results for Design Addons

**Comment by jarabroz** [comment]
#27 WS operations for results are released

**Comment by LakuszJ** [comment]
Thank You @jarabroz , very nice improvement !
My code need some rebuild but I'm really glad.
